### ISSUE TITLE
loss calculation problem

### ISSUE THREAD

**Issue by vcvishal** [notha99y/UNet#1]
after 5 epoch when i ran load_weights_and_test.py
this error occured

Traceback (most recent call last):
  File "src/load_weights_and_test.py", line 144, in <module>
    loss = weights_names[0].split(".")[1].split("-")[1] + "." + weights_names[0].split(".")[2]
IndexError: list index out of range

how to solve it
thank you

**Comment by notha99y** [comment]
Hi @vcvishal 
Sorry for the delayed response. Could you provide more details on this? I am unable to reproduce your error. 

Thanks
