### ISSUE TITLE
layers and surfaces labels

### ISSUE THREAD

**Issue by favaleh70** [notha99y/UNet#2]
I read the code completely but I did not understand how layers and surfaces labels were used?
I want to use this code for my own application. I don't know how to create these 2 labels. If I have just regions labels does it work?
Thanks

**Comment by notha99y** [comment]
Hi,
I apologize for the delayed response. 

Yes, you are right that I did not use the layers and surfaces labels. As this is a semantic segmentation task, I only used the regions labels. 

Please refer to this http://dags.stanford.edu/projects/scenedataset.html for more information to how to use the surfaces and layers labels.

Thanks

**Comment by favaleh70** [comment]
Thank you very much for guidance. I did not use layers and surfaces. It
was not necessary. Thank you very much for your code, I used it
successfully in my project.
 Best regards
Fatemeh Valeh

در تاریخ ۳۰ دسامبر ۲۰۱۹ ۶:۲۵ ق.ظ، "Ren Jie" <notifications@github.com> نوشت:

Closed #2 <https://github.com/notha99y/UNet/issues/2>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/notha99y/UNet/issues/2?email_source=notifications&email_token=ANM5QENQS7QYHNJ43EHILC3Q3FPLBA5CNFSM4I53JRZKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOVWRA27Y#event-2913078655>,
or unsubscribe
